### ISSUE TITLE
Alerts and Feed

### ISSUE THREAD

**Issue by alexeyinkin** [Rexios80/pub_stats#2]
### Popularity

With high popularity, every percent is a huge achievement. Sometimes I tweet something like 'We are +1%!', so I want to learn it as soon as it happens. Also a drop in popularity may mean call for action.

### Dependencies

If a new package starts to depend on mine, it is good news. If the package is popular, I may want to announce it. If a package has dropped the dependency on mine, they may have switched to a competitor, and I need to at least ask them for feedback.

### Alerts

Ideally I want to subscribe go get that on my email as soon as that is detected.

### Feed

On a package page, I want to see a feed of such events in case I want to see the summary of what happened over say the last month instead of digging through separate emails.

**Comment by Rexios80** [comment]
I've been thinking about doing alerts for a while, but that would probably mean implementing real accounts (not a problem just work I haven't gotten to around to). I already have Discord alerts running for myself on the backend, but it's not currently scalable. One issue I see with storing a feed is it could drastically increase the size of the database which I'm trying to keep within the free Realtime Database tier since this project doesn't currently have any way to generate money.

Isn't the popularity chart basically the feed for popularity changes? Do you just want a feed for other things or do you see value in having it represented twice?

**Comment by Rexios80** [comment]
Another issue I see with keeping track of dependents is that it would require an order of magnitude more API calls to collect that data. The only way I see to get that information is to do a paginated search, and some packages have a _lot_ of pages of results.

**Comment by Rexios80** [comment]
I did a test and adding dependent tracking would add 58389 calls every run. There are 46931 so it's not that many more honestly I way overestimated. But still any piece of data we add that requires an extra API call adds at least as many API calls as there are packages.

**Comment by Rexios80** [comment]
@alexeyinkin You can now set up alerts on https://beta.pubstats.dev and they should work although I only implemented Discord webhooks for now

**Comment by Rexios80** [comment]
The alerts I implemented so far are for like count, popularity, and pub points

**Comment by Rexios80** [comment]
I implemented the rest of the alerts including dependents. I figured out how to get the dependency data from the API calls I was already making so it turned out to not be too bad. Package histories are implemented as well.

**Comment by Rexios80** [comment]
Closing since most of this is implemented. Please create additional issues for new alert methods.
